my_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from recipes import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('recipes.urls')),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True, template_name='recipes/registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='signup'),
    path('admin/', admin.site.urls)
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path, include

from . import views

app_name = 'recipes'
urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('search/tag/<int:tag_id>', views.search_tag, name='search_tag'),
    path('search/category/<int:category_id>', views.search_category, name='search_category'),
    path('recipes/<int:recipe_id>', views.detail, name='detail'),
    path('favorite/create', views.favorite_create, name='heart'),
    path('favorite/delete', views.favorite_destroy, name='unheart'),
    path('review/create', views.review_create, name='review_create')
]

recipes/models.py
import math
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class CommonModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    deleted = models.DateTimeField(null=True)

    class Meta:
        abstract = True

class NamedModel(CommonModel):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name
    
    class Meta:
        abstract = True

class UserRelationModel(CommonModel):
    recipe = models.ForeignKey('Recipe', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        abstract = True

# App models

class Category(NamedModel):
    pass
    
class Ingredient(NamedModel):
    def amount(self):
        return self.amount_set.all()[0].amount

    def units(self):
        return self.amount_set.all()[0].unit.name
    pass

class Tag(NamedModel):
    pass

class Unit(NamedModel):
    name = models.CharField(max_length=10)

class Recipe(CommonModel):
    title = models.CharField(max_length=50)
    description = models.TextField()
    steps = models.TextField()
    category = models.ForeignKey(Category, models.SET_NULL, blank=True, null=True)
    tag = models.ForeignKey(Tag, models.SET_NULL, blank=True, null=True)
    ingredients = models.ManyToManyField(Ingredient, through='Amount')
    user = models.ForeignKey(User, models.SET_NULL, null=True)
    visit_counter = models.IntegerField(default=0)
    image = models.ImageField(default=None, upload_to='recipes/')

    @classmethod
    def top_5_used(cls):
        return cls.objects.values('tag_id').annotate(count=models.Count('tag_id')).order_by('-count').values('tag_id', 'tag__name')[:5]

    @classmethod
    def top_popular(cls):
        return cls.objects.order_by('-visit_counter').values()[:3]

    @classmethod
    def recent_last(cls, number):
        return cls.objects.order_by('-created')[:number]

    @classmethod
    def top_5_rating(cls):
        return cls.objects.values().annotate(models.Avg('review__rate')).order_by('-review__rate__avg')[:5]

    @classmethod
    def search_query(self, query):
        if query:
            return self.objects.filter(        
                models.Q(title__icontains=query) |
                models.Q(description__icontains=query) |
                models.Q(steps__icontains=query) |
                models.Q(ingredients__name__icontains=query)
            ).order_by('-created').distinct('id')
        else:
            return self.objects.all()

    def __str__(self):
        return self.title

    def author(self):
        return self.user.username

    def time_dmy(self):
        temp_date = str(self.created).split(' ')[0].split('-')
        temp_date.reverse()
        return '-'.join(temp_date)

    def review_counter(self):
        return self.review_set.all().count()

    def avg_rate(self):
        if self.review_set.all().count() > 0:
            avg = float(self.review_set.aggregate(models.Avg('rate'))['rate__avg'])
            return round(avg, 1) if bool(avg) else 0
        else:
            return 0

    def counter_rate_by_range(self, value):
        range = {
            '0': models.Q(**{"%s__gte" % 'rate': 0}),
            '1': models.Q(**{"%s__gte" % 'rate': 0.5}) & models.Q(**{"%s__lt" % 'rate': 1.5}),
            '2': models.Q(**{"%s__gte" % 'rate': 1.5}) & models.Q(**{"%s__lt" % 'rate': 2.5}),
            '3': models.Q(**{"%s__gte" % 'rate': 2.5}) & models.Q(**{"%s__lt" % 'rate': 3.5}),
            '4': models.Q(**{"%s__gte" % 'rate': 3.5}) & models.Q(**{"%s__lt" % 'rate': 4.5}),
            '5': models.Q(**{"%s__gte" % 'rate': 4.5}) & models.Q(**{"%s__lte" % 'rate': 5})
        }
        return self.review_set.filter(range[str(value)]).count()

    def percentage(self, poblation, total):
        return math.floor((poblation / total) * 100) if total > 0 else 0

    def rating_table_calculation(self):
        results = []
        total_rates = self.counter_rate_by_range(0)

        for i in reversed(range(1,6)):
            results.append(self.percentage(self.counter_rate_by_range(i), total_rates))
        
        return results

class Amount(CommonModel):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    amount = models.FloatField()
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE, null=False)

class Favorite(UserRelationModel):
    pass

class Review(UserRelationModel):
    content = models.TextField()
    rate = models.DecimalField(decimal_places=1, max_digits=2)

recipes/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    username = forms.CharField(label="", required=True, widget=forms.TextInput(attrs={'class': "form-control text-center", 'placeholder': "Username"}))
    email = forms.EmailField(label="", required=True, widget=forms.EmailInput(attrs={'class': "form-control text-center", 'placeholder': "Email"}))
    password1 = forms.CharField(label="", required=True, widget=forms.PasswordInput(attrs={'class': "form-control text-center", 'placeholder': "Password"}))
    password2 = forms.CharField(label="", required=True, widget=forms.PasswordInput(attrs={'class': "form-control text-center", 'placeholder': "Password Confirmation"}))

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(SignUpForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

recipes/views.py
import json
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, reverse, redirect
from django.contrib.auth import login
from django.contrib import messages
from .forms import SignUpForm

# Create your views here.
from django.db import models
from .models import Category, Ingredient, Tag, Unit, Recipe, Amount, Favorite, Review

def index(request):
    tags = Tag.objects.values()
    categories = Category.objects.values()
    recent_recipes = Recipe.recent_last(9)
    top_tags = Recipe.top_5_used()
    popular_recipes = Recipe.top_popular()
    top_recipes = Recipe.top_5_rating()

    context = {
        'tags': tags,
        'categories': categories,
        'top_tags': top_tags,
        'popular_recipes': popular_recipes,
        'recent_recipes': recent_recipes,
        'top_recipes': top_recipes
    }

    return render(request, 'recipes/index.html', context)

def detail(request, recipe_id):
    tags = Tag.objects.values()
    categories = Category.objects.all()
    recipe = Recipe.objects.get(pk=recipe_id)
    top_tags = Recipe.top_5_used()
    popular_recipes = Recipe.top_popular()
    reviews = recipe.review_set.all()

    context = {
        'recipe': recipe,
        'tags': tags,
        'categories': categories,
        'top_tags': top_tags,
        'popular_recipes': popular_recipes,
        'reviews': reviews
    }

    return render(request, 'recipes/detail.html', context)

def search(request):
    q = request.GET['q']
    
    recipes = Recipe.search_query(q)
    tags = Tag.objects.values()
    categories = Category.objects.values()
    top_tags = Recipe.top_5_used()
    popular_recipes = Recipe.top_popular()

    context = {
        'recipes': recipes,
        'top_tags': top_tags,
        'popular_recipes': popular_recipes,
        'tags': tags,
        'categories': categories,
        'query': f"Search: {q}"
    }

    return render(request, 'recipes/search/search.html', context)

def search_tag(request, tag_id):
    recipes = Recipe.objects.filter(tag=tag_id)
    tags = Tag.objects.values()
    categories = Category.objects.values()
    top_tags = Recipe.top_5_used()
    popular_recipes = Recipe.top_popular()
    tag = Tag.objects.get(pk=tag_id)

    context = {
        'recipes': recipes,
        'top_tags': top_tags,
        'popular_recipes': popular_recipes,
        'tags': tags,
        'categories': categories,
        'query': f"Tag: {tag.name}"
    }

    return render(request, 'recipes/search/search.html', context)

def search_category(request, category_id):
    recipes = Recipe.objects.filter(category=category_id)
    tags = Tag.objects.values()
    categories = Category.objects.values()
    top_tags = Recipe.top_5_used()
    popular_recipes = Recipe.top_popular()
    category= Category.objects.get(pk=category_id)

    context = {
        'recipes': recipes,
        'top_tags': top_tags,
        'popular_recipes': popular_recipes,
        'tags': tags,
        'categories': categories,
        'query': f"Category: {category.name}"
    }

    return render(request, 'recipes/search/search.html', context)

def favorite_create(request):
    data = json.loads(request.body)
    Favorite.objects.create(recipe_id=int(data['recipe_id']), user_id=request.user.id)
    
    return HttpResponse(data)

def favorite_destroy(request):
    data = json.loads(request.body)
    Favorite.objects.filter(recipe_id=int(data['recipe_id']), user_id=request.user.id).delete()

    return HttpResponse(data)

def review_create(request):
    review = Review.objects.create(
                recipe_id=int(request.POST['recipe_id']),
                user_id=int(request.POST['user_id']),
                rate=float(request.POST['rate']),
                content=request.POST['content']
            )
    return HttpResponseRedirect(reverse('recipes:detail', args=(int(review.recipe_id),)))

def register(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, f"Welcome {user.username}")
            return HttpResponseRedirect("/")
        messages.error(request, "Invalid data provided")
    else:
        form = SignUpForm()
    return render (request=request, template_name="recipes/registration/register.html", context={"form": form})

templates/recipes/detail/_ingredients_list.html
<ul class="ingredients-list">
    <li class="empty-li"></li>
    <li class="empty-li"></li>
    {% for amount in amounts %}
      <li>{{ amount.amount }} {{ amount.unit.name }} {{ amount.ingredient.name }}</li>
    {% endfor %}
    <li class="empty-li"></li>
    <li class="empty-li"></li>
  </ul>

templates/recipes/detail/_recipe_form_review.html
{% load recipes_extras %}
<div id="reviewForm">
    <form action="{% url 'recipes:review_create' %}" method="post"> {% csrf_token %}

      <input type="hidden" name="recipe_id" value="{{ recipe.id }}">
      <input type="hidden" name="user_id" value="{{ user.id }}">

      <div class="form-group row review-form-rate">
        <div class="col-2">
          {% star_rating 0 %}
        </div>
        <div class="col-8">
            <input type="range" name="rate" class="form-control custom-range" step="0.5" min="0.0" max="5.0" />
        </div>
        <div class="col-2">
          {% star_rating 5 %}
        </div>
      </div>
      <div class="row text-center">
        {% star_rating 3 %}
      </div>
  
      <div class="form-group review-form-content">
        <input type="text" name="content" class="form-control" placeholder="Share your thoughts" />
      </div>
  
      <div class="form-group review-form-buttom">
        <input type="submit" class="btn" value="Send" />
      </div>
    </form>
  </div>

templates/recipes/detail/_recipe_rating.html
{% load recipes_extras %}

<div id="recipeReviewsStatistics" class="row">

    <div class="col text-center">
      <h1 class="m-0">{{ avg_value }}</h1>
      {% star_rating avg_value %}
      <h5>Average Rating</h5>
    </div>
  
    <div class="col">
      {% for value in values %}
        <div class="progress my-2">
          <div class="progress-bar bg-success" role="progressbar" style="width:{{ value }}%"></div>
        </div>
      {% endfor %}
    </div>
  
    <div class="col">
      {% for value in values %}
        <div class="row">
          <div class="col">
            {% star_rating foorloop.counter0|add:"5" %}
          </div>
          <div class="col">
            <span>{{ value }}%</span>
          </div>
        </div>
      {% endfor %}
    </div>
</div>

templates/recipes/detail/_recipe_review_media.html
{% load recipes_extras %}
{% load static %}
<li>
  <div class="row">
    <div class="col-2 review-header">
      <img class="review-avatar" src="{% static 'recipes/avatar_default.png' %}" style="height:65px; width:65px;">
      <div class="review-stars">
        {% star_rating review.rate %}
      </div>
    </div>
    <div class="col-10">
      <div class="card-body">
          <div class="row review-info">
            <h5 class="col-10 review-author">{{ review.user.username }}</h5>
            <p class="col-2 review-date">{{ review.created }}</p>
          </div>
          <p class="card-text review-content">{{ review.content }}</p>
      </div>
    </div>
  </div>
</li>
<hr class="hr-list">

templates/recipes/detail/_recipe_reviews.html
<ul id="recipeReviewsList" class="list-unstyled">
    {% for review in reviews %}
        {% include "./_recipe_review_media.html" with review=review %}
    {% endfor %}
</ul>