my_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from recipes import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('recipes.urls')),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True, template_name='recipes/registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='signup'),
    path('admin/', admin.site.urls)
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path, include

from . import views

app_name = 'recipes'
urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('search/tag/<int:tag_id>', views.search_tag, name='search_tag'),
    path('search/category/<int:category_id>', views.search_category, name='search_category'),
    path('recipes/<int:recipe_id>', views.detail, name='detail'),
    path('favorite/create', views.favorite_create, name='heart'),
    path('favorite/delete', views.favorite_destroy, name='unheart'),
    path('review/create', views.review_create, name='review_create')
]

recipes/models.py
import math
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class CommonModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    deleted = models.DateTimeField(null=True)

    class Meta:
        abstract = True

class NamedModel(CommonModel):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name
    
    class Meta:
        abstract = True

class UserRelationModel(CommonModel):
    recipe = models.ForeignKey('Recipe', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        abstract = True

# App models

class Category(NamedModel):
    pass
    
class Ingredient(NamedModel):
    def amount(self):
        return self.amount_set.all()[0].amount

    def units(self):
        return self.amount_set.all()[0].unit.name
    pass

class Tag(NamedModel):
    pass

class Unit(NamedModel):
    name = models.CharField(max_length=10)

class Recipe(CommonModel):
    title = models.CharField(max_length=50)
    description = models.TextField()
    steps = models.TextField()
    category = models.ForeignKey(Category, models.SET_NULL, blank=True, null=True)
    tag = models.ForeignKey(Tag, models.SET_NULL, blank=True, null=True)
    ingredients = models.ManyToManyField(Ingredient, through='Amount')
    user = models.ForeignKey(User, models.SET_NULL, null=True)
    visit_counter = models.IntegerField(default=0)
    image = models.ImageField(default=None, upload_to='recipes/')

    @classmethod
    def top_5_used(cls):
        return cls.objects.values('tag_id').annotate(count=models.Count('tag_id')).order_by('-count').values('tag_id', 'tag__name')[:5]

    @classmethod
    def top_popular(cls):
        return cls.objects.order_by('-visit_counter').values()[:3]

    @classmethod
    def recent_last(cls, number):
        return cls.objects.order_by('-created')[:number]

    @classmethod
    def top_5_rating(cls):
        return cls.objects.values().annotate(models.Avg('review__rate')).order_by('-review__rate__avg')[:5]

    @classmethod
    def search_query(self, query):
        if query:
            return self.objects.filter(        
                models.Q(title__icontains=query) |
                models.Q(description__icontains=query) |
                models.Q(steps__icontains=query) |
                models.Q(ingredients__name__icontains=query)
            ).order_by('-created').distinct('id')
        else:
            return self.objects.all()

    def __str__(self):
        return self.title

    def author(self):
        return self.user.username

    def time_dmy(self):
        temp_date = str(self.created).split(' ')[0].split('-')
        temp_date.reverse()
        return '-'.join(temp_date)

    def review_counter(self):
        return self.review_set.all().count()

    def avg_rate(self):
        if self.review_set.all().count() > 0:
            avg = float(self.review_set.aggregate(models.Avg('rate'))['rate__avg'])
            return round(avg, 1) if bool(avg) else 0
        else:
            return 0

    def counter_rate_by_range(self, value):
        range = {
            '0': models.Q(**{"%s__gte" % 'rate': 0}),
            '1': models.Q(**{"%s__gte" % 'rate': 0.5}) & models.Q(**{"%s__lt" % 'rate': 1.5}),
            '2': models.Q(**{"%s__gte" % 'rate': 1.5}) & models.Q(**{"%s__lt" % 'rate': 2.5}),
            '3': models.Q(**{"%s__gte" % 'rate': 2.5}) & models.Q(**{"%s__lt" % 'rate': 3.5}),
            '4': models.Q(**{"%s__gte" % 'rate': 3.5}) & models.Q(**{"%s__lt" % 'rate': 4.5}),
            '5': models.Q(**{"%s__gte" % 'rate': 4.5}) & models.Q(**{"%s__lte" % 'rate': 5})
        }
        return self.review_set.filter(range[str(value)]).count()

    def percentage(self, poblation, total):
        return math.floor((poblation / total) * 100) if total > 0 else 0

    def rating_table_calculation(self):
        results = []
        total_rates = self.counter_rate_by_range(0)

        for i in reversed(range(1,6)):
            results.append(self.percentage(self.counter_rate_by_range(i), total_rates))
        
        return results

class Amount(CommonModel):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    amount = models.FloatField()
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE, null=False)

class Favorite(UserRelationModel):
    pass

class Review(UserRelationModel):
    content = models.TextField()
    rate = models.DecimalField(decimal_places=1, max_digits=2)

recipes/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    username = forms.CharField(label="", required=True, widget=forms.TextInput(attrs={'class': "form-control text-center", 'placeholder': "Username"}))
    email = forms.EmailField(label="", required=True, widget=forms.EmailInput(attrs={'class': "form-control text-center", 'placeholder': "Email"}))
    password1 = forms.CharField(label="", required=True, widget=forms.PasswordInput(attrs={'class': "form-control text-center", 'placeholder': "Password"}))
    password2 = forms.CharField(label="", required=True, widget=forms.PasswordInput(attrs={'class': "form-control text-center", 'placeholder': "Password Confirmation"}))

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(SignUpForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

recipes/views.py
import json
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, reverse, redirect
from django.contrib.auth import login
from django.contrib import messages
from .forms import SignUpForm

# Create your views here.
from django.db import models
from .models import Category, Ingredient, Tag, Unit, Recipe, Amount, Favorite, Review

def index(request):
    tags = Tag.objects.values()
    categories = Category.objects.values()
    recent_recipes = Recipe.recent_last(9)
    top_tags = Recipe.top_5_used()
    popular_recipes = Recipe.top_popular()
    top_recipes = Recipe.top_5_rating()

    context = {
        'tags': tags,
        'categories': categories,
        'top_tags': top_tags,
        'popular_recipes': popular_recipes,
        'recent_recipes': recent_recipes,
        'top_recipes': top_recipes
    }

    return render(request, 'recipes/index.html', context)

def detail(request, recipe_id):
    tags = Tag.objects.values()
    categories = Category.objects.all()
    recipe = Recipe.objects.get(pk=recipe_id)
    top_tags = Recipe.top_5_used()
    popular_recipes = Recipe.top_popular()
    reviews = recipe.review_set.all()

    context = {
        'recipe': recipe,
        'tags': tags,
        'categories': categories,
        'top_tags': top_tags,
        'popular_recipes': popular_recipes,
        'reviews': reviews
    }

    return render(request, 'recipes/detail.html', context)

def search(request):
    q = request.GET['q']
    
    recipes = Recipe.search_query(q)
    tags = Tag.objects.values()
    categories = Category.objects.values()
    top_tags = Recipe.top_5_used()
    popular_recipes = Recipe.top_popular()

    context = {
        'recipes': recipes,
        'top_tags': top_tags,
        'popular_recipes': popular_recipes,
        'tags': tags,
        'categories': categories,
        'query': f"Search: {q}"
    }

    return render(request, 'recipes/search/search.html', context)

def search_tag(request, tag_id):
    recipes = Recipe.objects.filter(tag=tag_id)
    tags = Tag.objects.values()
    categories = Category.objects.values()
    top_tags = Recipe.top_5_used()
    popular_recipes = Recipe.top_popular()
    tag = Tag.objects.get(pk=tag_id)

    context = {
        'recipes': recipes,
        'top_tags': top_tags,
        'popular_recipes': popular_recipes,
        'tags': tags,
        'categories': categories,
        'query': f"Tag: {tag.name}"
    }

    return render(request, 'recipes/search/search.html', context)

def search_category(request, category_id):
    recipes = Recipe.objects.filter(category=category_id)
    tags = Tag.objects.values()
    categories = Category.objects.values()
    top_tags = Recipe.top_5_used()
    popular_recipes = Recipe.top_popular()
    category= Category.objects.get(pk=category_id)

    context = {
        'recipes': recipes,
        'top_tags': top_tags,
        'popular_recipes': popular_recipes,
        'tags': tags,
        'categories': categories,
        'query': f"Category: {category.name}"
    }

    return render(request, 'recipes/search/search.html', context)

def favorite_create(request):
    data = json.loads(request.body)
    Favorite.objects.create(recipe_id=int(data['recipe_id']), user_id=request.user.id)
    
    return HttpResponse(data)

def favorite_destroy(request):
    data = json.loads(request.body)
    Favorite.objects.filter(recipe_id=int(data['recipe_id']), user_id=request.user.id).delete()

    return HttpResponse(data)

def review_create(request):
    review = Review.objects.create(
                recipe_id=int(request.POST['recipe_id']),
                user_id=int(request.POST['user_id']),
                rate=float(request.POST['rate']),
                content=request.POST['content']
            )
    return HttpResponseRedirect(reverse('recipes:detail', args=(int(review.recipe_id),)))

def register(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, f"Welcome {user.username}")
            return HttpResponseRedirect("/")
        messages.error(request, "Invalid data provided")
    else:
        form = SignUpForm()
    return render (request=request, template_name="recipes/registration/register.html", context={"form": form})

templates/recipes/_navbar.html
<nav id="homeNavbar" class="navbar navbar-expand-lg px-5">
    <a class="navbar-brand" href="{% url 'recipes:index' %}">Foodtopia</a>
    {% if user.is_authenticated %}
      <a href="#" class="navbar-brand">Welcome {{ user.username }}</a>
    {% endif %}
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ms-auto">        
        <!-- Tag -->
        <li class="nav-item active dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Tag</a>
          <ul class="dropdown-menu">
            {% for tag in tags %}
              <li><a class="dropdown-item" href="{% url 'recipes:search_tag' tag.id %}">{{ tag.name }}</a></li>
            {% endfor %}
          </ul>
        </li>

        <!-- Category -->
        <li class="nav-item active dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Category</a>
          <ul class="dropdown-menu">
            {% for category in categories %}
              <li><a class="dropdown-item" href="{% url 'recipes:search_category' category.id %}">{{ category.name }}</a></li>
            {% endfor %}
          </ul>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Log In</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  

templates/recipes/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}FullstackProject{% endblock %}</title>

    <script src="https://kit.fontawesome.com/bdf4dec60f.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'recipes/style.css' %}">

  </head>

  <body>
  
    {% include "./_navbar.html" %}

    <div id="principalBody">
      {% block content %}{% endblock %}
      {% include "./_info_section.html" %}
    </div>

    {% include "./_footer_section.html" %}

  </body>
</html>

templates/recipes/detail.html
{% extends 'recipes/base.html' %}
{% load recipes_extras %}
{% load static %}

{% block content %}
    <div id="currentRecipe">
    
        <h2 class="recipe-title">{{ recipe.title }}</h2>
        
        <div class="recipe-header">
            <span class="recipe-author">
                <span class="recipe-author-label">
                    <i class="fas fa-user-circle"></i>
                    Posted by
                </span>
                <span class="recipe-author-name">
                    {{ recipe.author }}
                </span>
            </span>
            <span class="recipe-timestamp">
                <span class="recipe-timestamp-label">
                    <i class="far fa-clock"></i>
                    Posted at
                </span>
                <span class="recipe-timestamp-time">
                    {{ recipe.time_dmy }}
                </span>
            </span>
            <span class="recipe-comments">
                <i class="fas fa-comments"></i>
                {{ recipe.review_counter }}
                Comments
            </span>
        </div>
    
        <div class="row row-cols-2">
            <!-- Picture -->
            <div class="col">
                {% if recipe.image %}
                    <img src="{{recipe.image}}" class="img-fluid">
                {% else %}
                    <img src="{% static 'recipes/image_default.jpg' %}" class="img-fluid">
                {% endif %}
            </div>
            <!-- Rating, buttons & Description -->
            <div class="col recipe-general">
                <div class="row recipe-rating-stars">
                    {% star_rating recipe.avg_rate %}
                </div>
        
            <!-- Button Group -->
    
                <div class="recipe-button-group row">
                    <div class="col">
                        <a href="#ratingBoard"> 
                            <div class="row">
                                <i class="fas fa-star icon-box-2"></i>
                            </div>
                            <div class="row">
                                <span>Rate</span>
                            </div>
                        </a>
                    </div>
    
                    <div class="col">
                        <a href="#reviewSection">
                            <div class="row">
                                <i class="fas fa-comment-alt icon-box-2"></i>
                            </div>
                            <div class="row">
                                <span>Comment</span>
                            </div>
                        </a>
                    </div>
    
                    <div class="col">
                        <div class="row">
                            {% if user.is_authenticated %}
                                {% favorite_mark user recipe.id "icon-box-2" %}
                            {% else %}
                                <i id='heart-{{ recipe.id }}' class='far fa-heart icon-box-2'></i>
                            {% endif %}
                        </div>
                        <div class="row">
                            <span>Save</span>
                        </div>
                    </div>
    
                    <div class="col">
                        <div class="row">
                            <i class="fas fa-print icon-box-2"></i>
                        </div>
                        <div class="row">
                            <span>Print</span>
                        </div>
                    </div>
               </div>
                <h4>Description</h4>
                <p>{{ recipe.description }}</p>
            </div>
        </div>
    
    
        <div class="row recipe-preparation">
            <div class="col-6 recipe-ingredients">
                <h4> <i class="fas fa-pencil-alt"></i> Ingredients</h4>
                {% include "./detail/_ingredients_list.html" with amounts=recipe.amount_set.all %}
            </div>
        
            <div class="col-6 recipe-steps">     
                <h4> <i class="fas fa-clipboard-list"></i> Steps</h4>
                <div>
                {{ recipe.steps }}
                </div>
            </div>
        </div>
    
        <hr class="hr-list">
    
        <section id="ratingBoard" class="rating-board">
            {% include "./detail/_recipe_rating.html" with values=recipe.rating_table_calculation avg_value=recipe.avg_rate %}
        </section>
    
        <hr class="hr-list">
    
        <section id="reviewSection" class="review-section">
            <h3> Reviews </h3>
            {% if user.is_authenticated %}
                {% include "./detail/_recipe_form_review.html" with recipe=recipe %}
                <hr class="hr-list">
            {% endif %}
            
            {% include "./detail/_recipe_reviews.html" with reviews=reviews %}
        </section>
    </div>

{% endblock %}

templates/recipes/index.html
{% extends 'recipes/base.html' %}

{% block title %}{{ site_title }}{% endblock %}

{% block content %}
  <section id="topRecipes">
    {% include "./home/_carousel.html" with recipes=top_recipes %}
  </section>
  
  <section id="recentRecipes">
    <h2>Recent Recipes</h2>
    <div class="row row-cols-3">
      {% for recipe in recent_recipes %}
          {% include "./home/_recent_card.html" with recipe=recipe %}
      {% endfor %}
    </div>
  </section>
{% endblock %}